#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$0

# Retrieve resource usage statistics from Kubernetes
kubectl top $2 -n $1 | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $4}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "Resource: $2, Namespace: $1, Name: $NAME, CPU: $CPU, Memory: $MEMORY"
done
